### PR TITLE
Add GraphQL

### PR DESCRIPTION
**Pull request by zachschuermann**
Opening, but definitely still WIP. So far this adds two endpoints: `/gql` and `/giql`.  The `gql` endpoint is what actual queries will happen against, while `giql` spins up a nice frontend for experimentation (and docs [yay self-documenting]).  

I've re-defined our schema for the reviews and aggregated reviews. Now using `mongoengine` as an ORM so all the schema is just Python.  

Unfortunately, each schema can only be valid for a single collection soooo I was going to try to do some crazy stuff with metaclasses to get it to write our own classes but honestly the easiest thing might be to just migrate the database to my server and put everything in a single 'master' collection (one master for reviews and one for aggregated reviews). I think if we end up querying quite a bit we might see some speedup since the cluster on Atlas is actually pretty slow.   

Addressing #26 

Sample query to execute to get started:
```
{
  reviews (n: 100) {
    instructorFirstName
    courseNumber
    question
  }
}
```

### CODE REVIEW

**Comment by zachschuermann** [comment]
Need to add tests as well

**Comment by schuermannator** [comment]
Sample query to execute if anyone needs help getting started:
```
{
  reviews (n: 100) {
    instructorFirstName
    courseNumber
    question
  }
}
```

**Comment by samjett247** [comment]
Zach thanks for this work, it looks great. 

**Review Per Topic**:
- GiQL is super handy for developing the correct query, and thats an awesome tool for getting anyone started with accessing our data.
- The built in ORM is great.
- With regard to needing all data in one collection, I agree with you about merging the collections - It should be easy enough to just handle that during data loading then never have to mess with it again. We could write a little script to combine all collections into a single database in Mongo and call that at the end of data_loader.

- Migrating to serving on your server seems like a separate discussion. I'm fine with it if you want to, but I feel like keeping things on Atlas seems more robust? Don't have to worry about power outages or other weird things that could happen that would just be a pain to work through remotely (software upgrades, etc.) - Your server is still in Norman, right? It just seems like a lot of work for marginal benefit, as I think our current latency is totally fine. I mean if its something you want to do, I'm not gonna stop you, but I dont think its high priority. We currently have a few copies over our data in different DBs on Mongo (`ocr_db` and `reviews_db` each have the raw ratings, and `reviews_db` has the aggregated as well), and we're only using ~110 MB of storage. So we'd have to be super lax with our data storage to hit 512 MB.

**Next Tasks**
- I'm gonna write a script to combine all collections into a single collection in a new db, and we can use that for the gql queries, with plans to get all queries migrated over to that new db.
- I'll work on some unit tests.
- Another big thing is once we get these most recent reviews scraped we can stop worrying about reading data from the csv files; That'll be nice for simplifying our data pipelines.

@schuermannator I know your last day is Thursday so just don't worry about this stuff til then.

**Comment by zachschuermann** [comment]
Ok yea, the only reason I mentioned it is because I thought we would run out of "free" storage on Atlas. But Atlas is definitely the better/more robust option. Make sure to login to Atlas and take a look at storage there because I think its reporting closer to 300 MB in use. @samjett247

**Comment by zachschuermann** [comment]
Here is what its reporting right now:  

Screen Shot 2019-08-11 at 10 15 03 AM

**Comment by zachschuermann** [comment]
When I look online (through Atlas) it's reporting the `reviews-db` database is 267.7 MB... Not sure why there is a discrepancy with Compass.

**Comment by samjett247** [comment]
@schuermannator Should I review this; Is it good to go? I know it needs to get the most recent changes to master merged in, happy to do that if you'd like me to

**Comment by zachschuermann** [comment]
not yet, working on it after i eat

**Comment by samjett247** [comment]
Due to changes in the upstream line, everything is in reviews-db-v1 (database name) in aggregated_reviews (collection). Is this guy good for review @schuermannator ? Sorry if i missed it i thought we talked on the phone and you said it wasnt done yet.

**Comment by zachschuermann** [comment]
Yea sorry not done yet, I'll ping you after this is in better shape. I've got a bit of bandwidth so I'll update soon!

**Comment by samjett247** [comment]
Adding filtering as described here: https://www.howtographql.com/graphql-python/7-filtering/

**Comment by jlovoi** [comment]
Can we reopen this?

**Pull request closed without merging**
